# Generated by Django 3.0.5 on 2022-12-11 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='text',
            new_name='pizza_name',
        ),
    ]
