# Generated by Django 3.0.5 on 2022-12-12 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0007_remove_comment_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='pizzasModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_field', models.ImageField(upload_to='')),
            ],
        ),
    ]
