# Generated by Django 3.0.5 on 2022-12-12 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0008_pizzasmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pizzasModel',
        ),
    ]
